# ==============================================================================
# TOOLS-UMKM - PYTHON TOOLS CONFIGURATION (VPS SAFE / RECON ONLY)
# ==============================================================================
# Format: <package_name_on_pypi> <executable_name>
# ==============================================================================

uro uro
waymore waymore
xnLinkFinder xnLinkFinder
dirsearch dirsearch
arjun arjun
